# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: turbomessage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12turbomessage.proto\x12\x0cturbomessage\"N\n\x04User\x12\x15\n\x08username\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08password\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x0b\n\t_usernameB\x0b\n\t_password\"\xc2\x01\n\x04Mail\x12\x0f\n\x02id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x13\n\x06sender\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08receiver\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x14\n\x07subject\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x14\n\x07message\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x11\n\x04read\x18\x06 \x01(\x08H\x05\x88\x01\x01\x42\x05\n\x03_idB\t\n\x07_senderB\x0b\n\t_receiverB\n\n\x08_subjectB\n\n\x08_messageB\x07\n\x05_read\"*\n\x06Status\x12\x14\n\x07success\x18\x01 \x01(\x08H\x00\x88\x01\x01\x42\n\n\x08_success2\x9d\x04\n\x0cTurboMessage\x12\x38\n\ncreateUser\x12\x12.turbomessage.User\x1a\x14.turbomessage.Status\"\x00\x12\x38\n\nuserExists\x12\x12.turbomessage.User\x1a\x14.turbomessage.Status\"\x00\x12\x36\n\x08sendMail\x12\x12.turbomessage.Mail\x1a\x14.turbomessage.Status\"\x00\x12\x38\n\nmailInRead\x12\x12.turbomessage.Mail\x1a\x14.turbomessage.Status\"\x00\x12\x39\n\x0bmailOutRead\x12\x12.turbomessage.Mail\x1a\x14.turbomessage.Status\"\x00\x12:\n\x0c\x64\x65leteMailIn\x12\x12.turbomessage.Mail\x1a\x14.turbomessage.Status\"\x00\x12;\n\rdeleteMailOut\x12\x12.turbomessage.Mail\x1a\x14.turbomessage.Status\"\x00\x12\x38\n\nreadMailIn\x12\x12.turbomessage.User\x1a\x12.turbomessage.Mail\"\x00\x30\x01\x12\x39\n\x0breadMailOut\x12\x12.turbomessage.User\x1a\x12.turbomessage.Mail\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'turbomessage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=36
  _USER._serialized_end=114
  _MAIL._serialized_start=117
  _MAIL._serialized_end=311
  _STATUS._serialized_start=313
  _STATUS._serialized_end=355
  _TURBOMESSAGE._serialized_start=358
  _TURBOMESSAGE._serialized_end=899
# @@protoc_insertion_point(module_scope)
