# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import turbomessage_pb2 as turbomessage__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in turbomessage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TurboMessageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Registrar = channel.unary_unary(
                '/TURBOMESSAGE.TurboMessage/Registrar',
                request_serializer=turbomessage__pb2.Usuario.SerializeToString,
                response_deserializer=turbomessage__pb2.Status.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/TURBOMESSAGE.TurboMessage/Login',
                request_serializer=turbomessage__pb2.Usuario.SerializeToString,
                response_deserializer=turbomessage__pb2.Status.FromString,
                _registered_method=True)
        self.EnviarCorreo = channel.unary_unary(
                '/TURBOMESSAGE.TurboMessage/EnviarCorreo',
                request_serializer=turbomessage__pb2.Correo.SerializeToString,
                response_deserializer=turbomessage__pb2.Status.FromString,
                _registered_method=True)
        self.ObtenerBandejaSalida = channel.unary_unary(
                '/TURBOMESSAGE.TurboMessage/ObtenerBandejaSalida',
                request_serializer=turbomessage__pb2.NombreUsuario.SerializeToString,
                response_deserializer=turbomessage__pb2.ListadoCorreos.FromString,
                _registered_method=True)
        self.ObtenerBandejaEntrada = channel.unary_unary(
                '/TURBOMESSAGE.TurboMessage/ObtenerBandejaEntrada',
                request_serializer=turbomessage__pb2.NombreUsuario.SerializeToString,
                response_deserializer=turbomessage__pb2.ListadoCorreos.FromString,
                _registered_method=True)
        self.LeerCorreo = channel.unary_unary(
                '/TURBOMESSAGE.TurboMessage/LeerCorreo',
                request_serializer=turbomessage__pb2.CorreoId.SerializeToString,
                response_deserializer=turbomessage__pb2.Correo.FromString,
                _registered_method=True)
        self.EliminarCorreo = channel.unary_unary(
                '/TURBOMESSAGE.TurboMessage/EliminarCorreo',
                request_serializer=turbomessage__pb2.EliminarRequest.SerializeToString,
                response_deserializer=turbomessage__pb2.Status.FromString,
                _registered_method=True)


class TurboMessageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Registrar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnviarCorreo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerBandejaSalida(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerBandejaEntrada(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeerCorreo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EliminarCorreo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TurboMessageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Registrar': grpc.unary_unary_rpc_method_handler(
                    servicer.Registrar,
                    request_deserializer=turbomessage__pb2.Usuario.FromString,
                    response_serializer=turbomessage__pb2.Status.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=turbomessage__pb2.Usuario.FromString,
                    response_serializer=turbomessage__pb2.Status.SerializeToString,
            ),
            'EnviarCorreo': grpc.unary_unary_rpc_method_handler(
                    servicer.EnviarCorreo,
                    request_deserializer=turbomessage__pb2.Correo.FromString,
                    response_serializer=turbomessage__pb2.Status.SerializeToString,
            ),
            'ObtenerBandejaSalida': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerBandejaSalida,
                    request_deserializer=turbomessage__pb2.NombreUsuario.FromString,
                    response_serializer=turbomessage__pb2.ListadoCorreos.SerializeToString,
            ),
            'ObtenerBandejaEntrada': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerBandejaEntrada,
                    request_deserializer=turbomessage__pb2.NombreUsuario.FromString,
                    response_serializer=turbomessage__pb2.ListadoCorreos.SerializeToString,
            ),
            'LeerCorreo': grpc.unary_unary_rpc_method_handler(
                    servicer.LeerCorreo,
                    request_deserializer=turbomessage__pb2.CorreoId.FromString,
                    response_serializer=turbomessage__pb2.Correo.SerializeToString,
            ),
            'EliminarCorreo': grpc.unary_unary_rpc_method_handler(
                    servicer.EliminarCorreo,
                    request_deserializer=turbomessage__pb2.EliminarRequest.FromString,
                    response_serializer=turbomessage__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TURBOMESSAGE.TurboMessage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('TURBOMESSAGE.TurboMessage', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TurboMessage(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Registrar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TURBOMESSAGE.TurboMessage/Registrar',
            turbomessage__pb2.Usuario.SerializeToString,
            turbomessage__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TURBOMESSAGE.TurboMessage/Login',
            turbomessage__pb2.Usuario.SerializeToString,
            turbomessage__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnviarCorreo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TURBOMESSAGE.TurboMessage/EnviarCorreo',
            turbomessage__pb2.Correo.SerializeToString,
            turbomessage__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerBandejaSalida(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TURBOMESSAGE.TurboMessage/ObtenerBandejaSalida',
            turbomessage__pb2.NombreUsuario.SerializeToString,
            turbomessage__pb2.ListadoCorreos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerBandejaEntrada(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TURBOMESSAGE.TurboMessage/ObtenerBandejaEntrada',
            turbomessage__pb2.NombreUsuario.SerializeToString,
            turbomessage__pb2.ListadoCorreos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeerCorreo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TURBOMESSAGE.TurboMessage/LeerCorreo',
            turbomessage__pb2.CorreoId.SerializeToString,
            turbomessage__pb2.Correo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EliminarCorreo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TURBOMESSAGE.TurboMessage/EliminarCorreo',
            turbomessage__pb2.EliminarRequest.SerializeToString,
            turbomessage__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
